### ISSUE TITLE
Tiene errores

### ISSUE THREAD

**Issue by xareas** [signumsoftware/southwind#9]
al compilarlo da problemas con esta importacion

import VersionChangedAlert from "@framework/Frames/VersionChangedAlert"

**Comment by olmobrutall** [comment]
Hi @xareas , 

If I compile Southwind with the version of Framework (dfba2276362ee933df63d0ef9281487c8c8d6782) and Extensions (26b74e3964d282b429e27080140af1d7c17fb707) that he is pointing to, everything looks ok.

It is true however that it does not compile with the latest Framework (746cb04d18fa628f7583c8a04dd5c60b30d72679 ) and Extensions (1eabefecc25392d9d25db78da1286546f49dd745), but Southwind is not updated immediately after every change in Framework or Extensions. It typically takes a few day / weeks until it's updated. 

In this particular case I changed the default export to remember to add the new `VersionInfo` control in the different projects. 

Anyway, I just updated Southwind to the latest framework and fix the compile time error :)

https://github.com/signumsoftware/southwind/commit/4dc1a65f9636fd0670704c12d0937b9ad612c8fc

Welcome and thank you for notice!
